; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE2BC6A3-E1CE-42FE-BEB7-95F693483C2E}
AppName=ContentBlock
AppVersion=0.1.1
;AppVerName=ContentBlock 0.1.0
AppPublisher=Jonathan Michael Preiß
AppPublisherURL=https://github.com/kard3n/cblock
AppSupportURL=https://github.com/kard3n/cblock
AppUpdatesURL=https://github.com/kard3n/cblock
DefaultDirName={autopf}\ContentBlock
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=cblock_setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=cblock_icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\cblock\cblock.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "classifiers\*"; DestDir: "{app}\classifiers"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "config\*"; DestDir: "{app}\config"; Flags: onlyifdoesntexist
Source: "schemas\schema_sources.json"; DestDir: "{app}\schemas"; Flags: onlyifdoesntexist
Source: "templates\*"; DestDir: "{app}\templates"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dist\cblock\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "pyproject.toml"; DestDir: "{app}"; Flags: ignoreversion
Source: "cblock_icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\ContentBlock"; Filename: "{app}\cblock.exe"; IconFilename: "{app}\cblock_icon.ico"
Name: "{autodesktop}\ContentBlock"; Filename: "{app}\cblock.exe"; Tasks: desktopicon; IconFilename: "{app}\cblock_icon.ico"

[Run]
; Note: removed skipifsilent, so that ContentBlock can restart after install
Filename: "{app}\cblock.exe"; Description: "{cm:LaunchProgram,ContentBlock}"; Flags: nowait postinstall

